---
title: "nvidia_prediction_markdown"
author: "Naren Akurati"
date: "3 Juli 2018"
output: html_document
---

##Preliminary Analysis
```{r}
Sys.setenv(LANG = "en")
#Read in the data
xx80 <- read.csv("xx80.csv", sep = ";")
xx80
#Note that the only metrics we see grow linearly are transistor density, cuda core count, core speed, and processing power
#For cards with boost capabilities, we only consider the highest speeds, as performance benchmarks always bring out these speeds in the cards

#Play with linear model
library(ggplot2)
m1 <- lm(xx80$core_speed ~ as.Date(xx80$launch))
summary(m1)

#Plotting different variables that have positive correlation with performance
library(gridExtra)
p1 <- ggplot(xx80, aes(x = as.Date(launch), y = core_speed)) + geom_point() + geom_smooth(se=FALSE)
p2 <- ggplot(xx80, aes(x = as.Date(launch), y = cuda_cores)) + geom_point() + geom_smooth(se=FALSE)
p3 <- ggplot(xx80, aes(x = as.Date(launch), y = core_speed)) + geom_point() + geom_smooth(se=FALSE)
p4 <- ggplot(xx80, aes(x = as.Date(launch), y = processing_power_single)) + geom_point() + geom_smooth(se=FALSE)

grid.arrange(p1,p2,p3,p4, ncol =2, nrow =2)

transistor_density <- xx80$transistors_millions/xx80$die_size
transistor_density
#million transistors per square mm

#Moore's law predicts that the number of transistors per square inch doubles each year

#1 square mm = 0.00155 square inch
scaled_transistor_density <- xx80$transistors_millions*1000000/xx80$die_size*0.00155
scaled_transistor_density
#this is in number of transistors per square inch

#moore's predicted transistor density
moore_predicted_scaled_transistory_density <- rep(scaled_transistor_density[1], 7) * c(1,2,4,8,16,32,64)
moore_predicted_scaled_transistory_density

moore_dates <- c("2009-01-08", "2011-01-08", "2013-01-08", "2015-01-08", "2017-01-08", "2019-01-08", "2021-01-08")

transistor_df <- data.frame("date" = c(as.Date(xx80$launch), as.Date(moore_dates)), "transistors" = c(scaled_transistor_density, moore_predicted_scaled_transistory_density), "type" = c(rep("real", 7), rep("moore", 7))) 
transistor_df

nvidia_transistors <- data.frame("date" = as.Date(xx80$launch), "transistors" = scaled_transistor_density)
moore_transistors <- data.frame("date" = as.Date(moore_dates), "transistors" = moore_predicted_scaled_transistory_density)

nvidia_transistor_model <- lm(sqrt(transistors) ~ date, data = nvidia_transistors)
summary(nvidia_transistor_model)

nvidia_transistor_model2 <- lm(transistors ~ date, data = nvidia_transistors)
summary(nvidia_transistor_model2)

moore_transistor_model <- lm(log(transistors) ~ date, data = moore_transistors)
summary(moore_transistor_model)

library(car)
powerTransform(nvidia_transistors[,2])

#predicted performance boost by transistor density through nvidia linear model
predict(nvidia_transistor_model2, newdata = data.frame("date" = as.Date("2018-08-01")), type = "response")/nvidia_transistors[7,2]

#predicted performance boost by transistor density through nvidia transformed model
predict(nvidia_transistor_model, newdata = data.frame("date" = as.Date("2018-08-01")), type = "response")^2/nvidia_transistors[7,2]

#predicted performance boost by transistor density through moore's law
#starting point for moore's law is gtx 280
exp(predict(moore_transistor_model, newdata = data.frame("date" = as.Date("2018-08-01")), type = "response"))/nvidia_transistors[7,2]

ggplot(transistor_df, aes(x = date, y = transistors, color = type)) + geom_point() + geom_smooth(se=FALSE)
```

##Bringing in Synthetic benchmarks
```{r}
#3DMark Graphics Score
threedmark_score <- c(NA, 3649, 4952, 7672, 10490, 13898, 21787)
threedmark_score
xx80$processing_power_single
```
